# Common model settings
num_input_channels: 3
num_aux_input_channels: 7
num_feature_map_channels: 256
curve_order: raster
num_gradient_checkpoints: 0

# Discriminator settings
discriminator:
  use_multiscale_discriminator: false

# Loss weights
losses:
  l1_loss_w: 1.0
  gan_loss_w: 0.005
  gp_loss_w: 10
  use_lpips_loss: false
  lpips_loss_w: 0.1
  use_ssim_loss: false
  ssim_loss_w: 0.1
