defaults:
  - common

name: mamba

mamba:
  num_layers: 5
  d_state: 64 # Dimension of the state space in Mamba layers
  d_conv: 4 # Dimension of the convolution kernel
  expansion: 4 # Channel expansion factor in each layer
  num_gcp: 0 # Number of gradient checkpoints
