# Training settings
batch_size: 8
epochs: 12
deterministic: true
save_interval: 1
num_saved_imgs: 6

# Optimizer settings
optim:
  _target_: torch.optim.Adam
  lr: 1e-4
  betas: [0.9, 0.999]

# Learning rate scheduler
scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones: [3, 6, 9]
  gamma: 0.5

# Generator/Discriminator learning rates
lrG: 1e-4
lrD: 1e-4
lr_gamma: 0.5
lr_milestone: 3
