defaults:
  - _self_
  - model: afgsa
  - data: default
  - trainer: default

_base_pattern: p${data.patches.patch_size}_n${data.patches.num_patches}_r${data.images.scale}
_dir_base_pattern: ${model.name}_${_base_pattern}

# Global settings
seed: 990819
data_ratio: 0.95
run_num: -1

# File paths
paths:
  root: ${hydra:runtime.cwd}
  output_dir: ${pht_run_dirs:outputs, ${_dir_base_pattern}, ${hydra:sweep.subdir}, ${run_num}, false}

# Hydra configuration
hydra:
  run:
    dir: ${pht_run_dirs:outputs, ${_dir_base_pattern}, ${hydra:sweep.subdir}, ${run_num}, false}
  job:
    chdir: false
  sweep:
    dir: ${pht_run_dirs:outputs, ${_dir_base_pattern}, none, ${run_num}, true}
    subdir: ${hydra.job.override_dirname}
