defaults:
  - _self_
  - model: afgsa
  - data: default
  - trainer: default

seed: 990819

data_ratio: 0.95

paths:
  root: ${hydra:runtime.cwd}
  out_dir: ${hydra:run.dir}

hydra:
  run:
    dir: runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false
  sweep:
    dir: multiruns/${now:%Y-%m-%d}
